In [106]:
import pandas as pd

In [107]:
dataset = pd.read_csv("insurance_pre.csv")

In [108]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [109]:
dataset = pd.get_dummies(dataset, drop_first = True)

In [110]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [111]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [112]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [113]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [114]:
dependent = dataset[['charges']]

In [115]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [116]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.30, random_state = 0)

In [117]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(criterion = 'poisson', n_estimators = 100, random_state = 0)
regressor = regressor.fit(x_train, y_train)

#1. criterion = 'squared_error', n_estimators = 50    -> 0.8495860472309916
#2. criterion = 'squared_error', n_estimators = 100   -> 0.8537074492312178
#3. criterion = 'absolute_error', n_estimators = 50   -> 0.8533104199010396
#4. criterion = 'absolute_error', n_estimators = 100  -> 0.8522171666048011
#5. criterion = 'friedman_mse', n_estimators = 50     -> 0.8498058213339406
#6. criterion = 'friedman_mse', n_estimators = 100    -> 0.8540807721486975    <<<<<<
#7. criterion = 'poisson', n_estimators = 50          -> 0.8491113222296434
#8. criterion = 'poisson', n_estimators = 100         -> 0.8526481325996583

/opt/anaconda3/lib/python3.13/site-packages/sklearn/base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [118]:
y_pred = regressor.predict(x_test)

In [119]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)

In [120]:
r_score

0.8526481325996583