In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first = True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [9]:
dependent = dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size = 0.30, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test  = sc.transform(x_test)

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid = {'criterion' : ['absolute_error', 'friedman_mse', 'poisson', 'squared_error'], 'max_features' : ['sqrt', 'log2'], 'splitter' : ['best', 'random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3, n_jobs = -1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['absolute_error', 'friedman_mse',
                                       'poisson', 'squared_error'],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [20]:
result = grid.cv_results_
print("The R_Score value for best parameter {}:", format(grid.best_params_))

The R_Score value for best parameter {}: {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'}

In [21]:
table = pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008513,0.000672,0.000918,0.000161,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.715160,0.681438,0.651267,0.560659,0.546956,0.631096,0.066406,3
1,0.006083,0.000713,0.000807,0.000146,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.788824,0.524514,0.671954,0.654599,0.419865,0.611951,0.127472,7
2,0.007857,0.000845,0.000991,0.000239,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.741536,0.561231,0.662876,0.692955,0.634215,0.658562,0.060253,2
3,0.005909,0.000684,0.000852,0.000101,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.690366,0.549237,0.674678,0.553791,0.560513,0.605717,0.063009,8
4,0.001430,0.000251,0.000587,0.000188,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.616511,0.591872,0.554377,0.455274,0.623644,0.568336,0.061500,14
5,0.001253,0.000229,0.000724,0.000168,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.694066,0.548987,0.572828,0.509147,0.646329,0.594271,0.066971,11
6,0.001429,0.000273,0.000555,0.000107,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.592616,0.595076,0.669701,0.531792,0.634422,0.604722,0.046179,9
7,0.001182,0.000244,0.000660,0.000260,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.765513,0.602725,0.609396,0.570339,0.524235,0.614442,0.081324,5
8,0.001592,0.000361,0.000487,0.000076,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.770469,0.598016,0.646235,0.666304,0.669651,0.670135,0.056310,1
9,0.001308,0.000233,0.000873,0.000327,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.655398,0.512492,0.641311,0.486763,0.667851,0.592763,0.076939,12
10,0.001763,0.000390,0.000769,0.000283,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.743220,0.568726,0.658320,0.454640,0.385385,0.562058,0.130294,15
11,0.001374,0.000360,0.000582,0.000150,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.631493,0.667742,0.574288,0.652475,0.573557,0.619911,0.039275,4
12,0.001624,0.000206,0.000491,0.000056,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.689976,0.717660,0.506070,0.485661,0.619773,0.603828,0.093972,10
13,0.001099,0.000249,0.000523,0.000145,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.711940,0.488077,0.608734,0.543452,0.509196,0.572280,0.080913,13
14,0.001220,0.000257,0.000421,0.000073,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.741771,0.679001,0.562925,0.571858,0.509313,0.612974,0.084722,6
15,0.000891,0.000045,0.000409,0.000019,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.732626,0.360989,0.568491,0.472537,0.463497,0.519628,0.125132,16

In [22]:
prediction_result = grid.predict([[43, 56, 2, 1, 1]])
prediction_result

array([48673.5588])