In [46]:
import pandas as pd

In [47]:
dataset = pd.read_csv("Social_Network_Ads.csv")

In [48]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [49]:
dataset = pd.get_dummies(dataset, dtype = int, drop_first=True)
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [50]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [51]:
dataset = dataset.drop("User ID", axis=1)
dataset.columns

Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [52]:
independent = dataset[['Gender_Male', 'Age', 'EstimatedSalary']]
independent

     Gender_Male  Age  EstimatedSalary
0              1   19            19000
1              1   35            20000
2              0   26            43000
3              0   27            57000
4              1   19            76000
..           ...  ...              ...
395            0   46            41000
396            1   51            23000
397            0   50            20000
398            1   36            33000
399            0   49            36000

[400 rows x 3 columns]

In [53]:
dependent = dataset[['Purchased']]
dependent

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [54]:
dataset["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [55]:
independent.shape

(400, 3)

In [56]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size = 1/3, random_state = 0)

In [57]:
from sklearn.svm import SVC

classifier = SVC(kernel = 'rbf', random_state = 0)
classifier = classifier.fit(x_train, y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [58]:
y_pred = classifier.predict(x_test)

In [59]:
from sklearn.metrics import confusion_matrix

confMatrix = confusion_matrix(y_test, y_pred)

In [60]:
from sklearn.metrics import classification_report

class_report = classification_report(y_test, y_pred)
print(class_report)

              precision    recall  f1-score   support

           0       0.76      0.96      0.85        85
           1       0.88      0.47      0.61        49

    accuracy                           0.78       134
   macro avg       0.82      0.72      0.73       134
weighted avg       0.81      0.78      0.76       134

In [61]:
print(confMatrix)

[[82  3]
 [26 23]]

In [62]:
classifier.predict([[40, 300, 1]])

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

array([0])